### ISSUE TITLE
Check not being run in PR

### ISSUE THREAD

**Issue by Panaetius** [fossapps/pr_label_enforcer#16]
We tried adding this app to our project, but the action doesn't get executed/doesn't show up in github on our test PR. See https://github.com/SwissDataScienceCenter/renku-python/pull/822 for the PR exhibiting the problem.

Is there some step we missed or what could cause this issue?

Thanks a lot!

**Comment by cyberhck** [comment]
```
version: '1'
invalidStatus: "pending"
labelRule:
  endsWith:
    - "g"
  values:
    - "bug"
    - "enhancement"
```
You need a file at: `.github/pr_labels.yml`, `endsWith` means any labels which ends with that value, `value` is exact value and `beginsWith` is any label which begins with value.

Once you have this PR merged, then it should start sending the checks in.

**Comment by cyberhck** [comment]
I've sent you a PR showing how to do, feel free to modify that :)

**Comment by Panaetius** [comment]
So `.github/pr_labels.yml` needs to be in `master` for it to work?

**Comment by cyberhck** [comment]
Yes

**Comment by Panaetius** [comment]
Thanks a lot. After merging to master it works :+1: 

We originally misread the documentation and thought that 
```
version: '1'
invalidStatus: "pending"
labelRule:
  endsWith:
    - "g"
```
would mean `invalidStatus` gets applied to any PR with labels matching any `labelRule`, instead of matching `labelRule` meaning it's valid and `invalidStatus` being applied when no rule matches (which makes much more sense in hindsight).

It's nothing big, but we originally envisioned having an Action using the `actions/labeler@v2` that would add a label `documentation:pending` when a PR is created, then then using PR Label Enforcer to do a negative check on that, so that PRs can only be merged once that label was removed. This would serve as a reminder on newly opened PRs so adding documentation doesn't get forgotten.

For now we'll do it the other way around, with only PRs that have `documentation:added` or `documentation:not_required` being mergeable. But it'd be really nice if PR Label Enforcer could allow such negative checks.

I'd imagine it being new rules like:

```
version: '1'
invalidStatus: "pending"
labelRule:
  doesntEndWith:
    - "g"
  doesntStartWith:
    - "g"
  not:
    - "wip"
```
Thank you again for your help :)
